Orders active record
wecodeio/empanadeitor pull request #10
Opened 2019-03-18 20:11 UTC by guidorombola

Guarda las órdenes en la base de datos.

2019-03-20 14:20 UTC, delucas requested changes

2019-03-20 14:20 UTC, delucas commented on app/controllers/orders_controller.rb
> +    @order = Order.find(params[:order_data][:id])
Esto no debería venir por parámetro en la url? Digo, ser el "id" simplemente?

2019-03-20 14:20 UTC, delucas commented on app/controllers/orders_controller.rb
> +    params[:order_new].permit!
`order_new` es un mal nombre

2019-03-20 14:20 UTC, delucas commented on config/routes.rb
>    post '/orders/finish', to: 'orders#finish', as: 'finish_order'
Esto deberia ser una ruta más dentro del resource.
```
resources :orders do
  post :finish on :member
end
```

2019-03-20 14:20 UTC, delucas commented on db/migrate/20190319175404_change_relationships.rb
> +class ChangeRelationships < ActiveRecord::Migration[5.2]
Para proximas veces, estos nombres son demasiado genéricos

2019-03-20 14:20 UTC, delucas commented on db/migrate/20190319181117_add_slug.rb
> +class AddSlug < ActiveRecord::Migration[5.2]
Para proximas veces, estos nombres son demasiado genéricos

2019-03-20 14:20 UTC, delucas commented on db/seeds.rb
> -Variety.create(place: canastita, name: '[Frita] Carne picada a cuchillo', price: 30.0)
bien por actualizar el seeds!

2019-03-20 15:10 UTC, guidorombola commented on app/controllers/orders_controller.rb
> +    @order = Order.find(params[:order_data][:id])
@delucas esto es porque la vista show envía dos cosas en un form: el id (que está como text input hidden) y el precio

2019-03-20 15:21 UTC, guidorombola commented on app/controllers/orders_controller.rb
> +    params[:order_new].permit!
Cambiado a `input_order`

2019-03-20 17:42 UTC, ceneon reviewed
Dejo unos comentarios menores

2019-03-20 17:42 UTC, ceneon commented on Gemfile.lock
> -      systemu (~> 2.6.2)
Mmmm pasó algo raro si hay modificaciones al Gemfile.lock y no al Gemfile. 
Es posible que se haya commiteado un cambio en el Gemfile en master sin su respectivo cambio en el Gemfile.lock, y por eso ahora da una diferencia en este PR.

2019-03-20 17:42 UTC, ceneon commented on app/controllers/orders_controller.rb
> +    @order = Order.find(params[:order_data][:id])
claro, pero por qué dentro de un `order_data` creo que es lo que Lucas pregunta

2019-03-20 17:42 UTC, ceneon commented on app/controllers/orders_controller.rb
> +    params[:input_order].permit!
El `permit` hace falta para pasarle a un objeto ActiveRecord una serie de campos todos de una, pero este no parece ser el caso 🤔

2019-03-20 17:42 UTC, ceneon commented on app/controllers/orders_controller.rb
> +    @order.place_name = @place.name
Entiendo que crearon `place_name`, `place_address` y `place_phone` para persistir esos valores incluso si el venue es modificado. 
Yo resolvería estas asignaciones (en new, create, etc) dentro de la clase Order, sino suena a algo que puede ser olvidado al usar un objeto de esa clase. 
Podría ser un callback en la inicialización o `before_create` por ejemplo.

2019-03-20 17:42 UTC, ceneon commented on Gemfile.lock
> -      systemu (~> 2.6.2)
El correr `bundle` en este branch (y estimo que en master también) da este error:

```Your Gemfile lists the gem byebug (>= 0) more than once.```

2019-03-21 15:40 UTC, guidorombola commented on app/controllers/orders_controller.rb
> +    @order = Order.find(params[:order_data][:id])
@ceneon si, me acabo de dar cuenta que es innecesario

2019-03-21 15:42 UTC, guidorombola commented on app/controllers/orders_controller.rb
> +    params[:input_order].permit!
@ceneon sin esto no te deja convertirlo a hash

2019-03-21 16:42 UTC, guidorombola commented on Gemfile.lock
> -      systemu (~> 2.6.2)
@ceneon listo, eliminada la redundancia

2019-03-21 18:21 UTC, delucas approved these changes

2019-03-21 18:21 UTC, delucas commented
:ship:

2019-03-21 18:24 UTC, merged