flash-message
wecodeio/empanadeitor pull request #13
Opened 2019-03-20 12:20 UTC by Lagofa

se agregaron mensages flash tanto a los lugares como a las variedades

2019-03-20 14:09 UTC, delucas commented
1. En la descripción del PR debería haber una imagen que muestre cómo se ven estas cosas ahora
2. No está bueno que los mensajes sean tan genéricos. Yo utilizaría una internacionalización por cada entidad. O si no, un string en el cuerpo del controller (no estamos haciendo esto multi-idioma aún)

2019-03-20 14:10 UTC, delucas requested changes
Mensajes demasiado genéricos! :(

2019-03-20 17:29 UTC, ceneon commented
¿Vamos a soportar otros idiomas? :P

2019-04-03 09:53 UTC, Lagofa commented
![Captura de pantalla de 2019-04-03 06-51-21](https://user-images.githubusercontent.com/7575736/55470005-26e22900-55dd-11e9-822c-c536e0ed9120.png)
![Captura de pantalla de 2019-04-03 06-51-48](https://user-images.githubusercontent.com/7575736/55470039-33ff1800-55dd-11e9-9aab-5d9e63d6dc5b.png)

2019-04-03 15:24 UTC, delucas approved these changes

2019-04-03 15:24 UTC, delucas commented
:+1: :shipit: 
(cuando arreglen los conflictos)

2019-04-03 15:35 UTC, merged