Admin creation
wecodeio/empanadeitor pull request #9
Opened 2019-03-15 20:07 UTC by guidorombola

Ordena las rutas correspondientes al administrador, provee una auntenticación básica y mejora estilos del sitio de administración.

2019-03-17 22:55 UTC, delucas requested changes
Sólo el cambio que pedí de comprobar si la variead se corresponde al lugar... más allá de eso, está muy bien.

2019-03-17 22:55 UTC, delucas commented on app/controllers/admin/varieties_controller.rb
> -    @places = Place.all
Deberian chequear la posible inconsistencia entre el `place_id` y el `variety_id` (pueden no corresponderse)

2019-03-17 22:55 UTC, delucas commented on db/migrate/20190315181221_remove_varieties_price.rb
> +    remove_column :varieties, :price
:ok_hand:

2019-03-18 16:57 UTC, ceneon reviewed
Muy bueno, está quedando como una app completa :) 
Dejo algunos comentarios.

2019-03-18 16:57 UTC, ceneon commented on app/controllers/admin/places_controller.rb
> +  http_basic_authenticate_with name: ENV['ID'], password: ENV['KEY']
:+1: Esta opción así no la conocía

2019-03-18 16:57 UTC, ceneon commented on app/controllers/admin/varieties_controller.rb
> +  layout 'admin_application'
Una sugerencia: Se podría hacer heredar todos los controllers de Admin de una clase común, así estas 2 líneas (y potencialmente otras más adelante) se aplican a todos de una vez.
La ventaja más que no escribir de nuevo estas líneas, es que hay menos chances de olvidarse de aplicar la seguridad en un futuro controller.

Usualmente lo creamos como `Admin::BaseController` y la definición de estos quedaría como `class Admin::VarietiesController < Admin::BaseController`

2019-03-18 16:57 UTC, ceneon commented on app/views/layouts/application.html.erb
> +  </div>-->
Mmmm esto debería borrarse, ya que no volverá a ir en el menú principal (el de cara al usuario)

2019-03-18 16:57 UTC, ceneon commented on config/routes.rb
> +    end
Acá es habitual tener definido un root del admin, así se puede entrar con `/admin` que es lo más común.

2019-03-18 16:57 UTC, ceneon commented on app/views/admin/places/index.html.erb
> +              <i class="fas fa-trash-alt"></i>
facheros los iconitos 😎

2019-03-18 19:23 UTC, guidorombola commented on app/views/layouts/application.html.erb
> +  </div>-->
Correcto, eliminados los comentarios

2019-03-18 19:33 UTC, guidorombola commented on app/controllers/admin/varieties_controller.rb
> +  layout 'admin_application'
Realizado

2019-03-18 19:53 UTC, delucas commented
:+1: MA!
:shipit:

2019-03-18 19:53 UTC, delucas approved these changes

2019-03-18 19:54 UTC, merged